version: '2'

services:

  portainer:
    image: portainer/portainer
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    ports:
    - 9000:9000
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ${DOCKERSTUFF_PATH}/portainer:/data

  nodered:
    # image: nodered/node-red-docker:rpi
    # image: nodered/node-red:2.2.3-12
    image: nodered/node-red
    container_name: nodered
    restart: unless-stopped
    volumes:
    - ${DOCKERSTUFF_PATH}/nodered/data:/data
    ports:
    - 1880:1880
    - 9898:9898/udp
    depends_on:
    - mqtt

  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    restart: unless-stopped
    ports:
    - 1883:1883
    - 9001:9001
    volumes:
    - ${DOCKERSTUFF_PATH}/mqtt/:/mosquitto/config
    - ${DOCKERSTUFF_PATH}/mqtt/:/mosquitto/data
    - ${DOCKERSTUFF_PATH}/mqtt/:/mosquitto/log

 # https://hub.docker.com/r/marthoc/deconz/
  deconz:
    image: marthoc/deconz
    container_name: deconz
    network_mode: host
    restart: always
    volumes:
    - ${DOCKERSTUFF_PATH}/deconz:/root/.local/share/dresden-elektronik/deCONZ
    devices:
    - /dev/ttyACM0
    environment:
    - DECONZ_WEB_PORT=80
    - DECONZ_WS_PORT=443
    - DEBUG_INFO=1
    - DEBUG_APS=0
    - DEBUG_ZCL=0
    - DEBUG_ZDP=0
    - DEBUG_OTAU=0
