
- id: leila_life360_event
  alias: Leila Life360 Event
  trigger:
  - entity_id: device_tracker.life360_leila
    from: 'on'
    platform: state
    to: 'off'
  - entity_id: device_tracker.life360_leila
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data_template:
      topic: '/homeassistant/life360'
      payload_template: "{{states.device_tracker.life360_leila.state}}"
    service: mqtt.publish
