
# https://www.home-assistant.io/docs/automation/trigger/#zone-trigger

- id: leila_leaving_home
  alias: leila_leaving_home
  trigger:
    entity_id: device_tracker.life360_leila
    event: leave
    platform: zone
    zone: zone.home
  condition: []
  action:
  - service: mqtt.publish
    data_template:
      topic: /homeassistant/life360
      payload_template: Leila leaving home    

# - id: leila_arrived_work
#   alias: leila_arrived_work
#   trigger:
#     entity_id: device_tracker.life360_leila
#     event: enter
#     platform: zone
#     zone: zone.leilas_work
#   action:
#   - data_template:
#       payload_template: Leila go to work
#       topic: /homeassistant/life360
#     service: mqtt.publish

- id: leila_left_work
  alias: leila_left_work
  trigger:
    entity_id: device_tracker.life360_leila
    event: leave
    platform: zone
    zone: zone.leilas_work
  action:
  - data_template:
      payload_template: Leila left work
      topic: /homeassistant/life360
    service: mqtt.publish
    
# - id: leila_arrived_willis_bus
#   alias: leila_arrived_willis_bus
#   trigger:
#     entity_id: device_tracker.life360_leila
#     event: enter
#     platform: zone
#     zone: zone.nw_willis_bus_stop
#   condition: []
#   action:
#   - data_template:
#       topic: /homeassistant/life360
#       payload_template: Leila arrived Willis St Bus
#     service: mqtt.publish

- id: leila_arrived_liqour_king
  alias: leila_arrived_liqour_king
  trigger:
    entity_id: device_tracker.life360_leila
    event: enter
    platform: zone
    zone: zone.outside_liquor_king
  action:
  - data_template:
      payload_template: Leila arrived Liqour King
      topic: /homeassistant/life360
    service: mqtt.publish

- id: leila_arrived_aroy_cuba
  alias: leila_arrived_aroy_cuba
  trigger:
    entity_id: device_tracker.life360_leila
    event: enter
    platform: zone
    zone: zone.aroy_cuba
  action:
  - data_template:
      payload_template: Leila arrived Aroy Cuba
      topic: /homeassistant/life360
    service: mqtt.publish

- id: leila_close_to_home
  alias: leila_close_to_home
  trigger:
    entity_id: device_tracker.life360_leila
    event: enter
    platform: zone
    zone: zone.home
  condition: []
  action:
  - service: mqtt.publish
    data_template:
      topic: /homeassistant/life360
      payload_template: Leila close to home    


