default_config:
#  tts:
#    - platform: google_translate
homeassistant:
  # Location required to calculate the time the sun rises and sets
  latitude: -41.295160
  longitude: 174.765340
  elevation: 100
  # Name of the location where Home Assistant is running
  name: Home
  # C for Celcius, F for Fahrenheit
  temperature_unit: C
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Pacific/Auckland
  unit_system: metric

# -group: !include groups.yaml
# -script: !include scripts.yaml
# discovery:

http:
  api_password: dietpi


mqtt:
  client_id: my_mqtt
  broker: 192.168.1.105 #:1883

mqtt mqtt_test:
  - platform: mqtt
    name: 'mqtt test'
    state_topic: "/device/test"
    state_on: "on"
    state_off: "off"

device_tracker:
  - platform: life360
    # https://www.home-assistant.io/components/life360/
    username: skelstar@gmail.com
    password: ec11225f87
    circles:
      include: [Family]

zone:
  - name: Home
    latitude: -41.295160
    longitude: 174.765340
    radius: 250
    icon: mdi:school

  - name: Daycare
    latitude: -41.288180
    longitude: 174.777670
    radius: 100
    icon: mdi:home

  - name: Outside Liquor King
    latitude: -41.293399
    longitude: 174.773497
    radius: 100

# configuration.yaml entry

automation: !include automations.yaml
#automation:
  # - alias: Leila leaving Daycare
  #   trigger:
  #     platform: state
  #     entity_id: device_tracker.life360_leila
  #     from: 'Daycare'
  #     to: 'no_home'
  #   action:
  #     - service: notify.notify
  #       data:
  #         message: Leila left Daycare

  # - alias: Bench motion detector turns light on
  #   trigger:
  #     - platform: event
  #       entity_id: binary_sensor.motion_bench
  #       from: 'off'
  #       to: 'on'
  #   action:
  #     - service: bedroomlights.turnon
  #       data:




# deconz key E09E33DE20



