default_config:

homeassistant:
  # Location required to calculate the time the sun rises and sets
  latitude: -41.295160
  longitude: 174.765340
  elevation: 100
  # Name of the location where Home Assistant is running
  name: Home
  # C for Celcius, F for Fahrenheit
  temperature_unit: C
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Pacific/Auckland
  unit_system: metric

  customize:
    device_tracker.life360_leila:
      friendly_name: Leila
    device_tracker.life360_seankelly:
      friendly_name: Finn

# -group: !include groups.yaml
# -script: !include scripts.yaml
# discovery:

# http:
#   api_password: dietpi
# WARNING (MainThread) [homeassistant.components.http] Configuring api_password via the http integration has been deprecated. Use the legacy api password auth provider instead. For instructions, see https://www.home-assistant.io/docs/authentication/providers/#legacy-api-password

logger:
  default: debug
    

mqtt:
  client_id: my_mqtt
  broker: 192.168.1.105

sensor:
  - platform: mqtt
    name: "front door vibration"
    state_topic: "/device/frontdoor-vibration"

binary_sensor:
  - platform: mqtt
    name: "Kitchen Lights"
    state_topic: "/device/smartsocket/SMTSKT05/event"
    # command_topic: "/homeassistant/lights/kitchenbench"
    value_template: "{%if is_state(entity_id,\"on\")-%}OFF{%-else-%}ON{%-endif%}"
  # - platform: mqtt
  #   name: "Kitchen Lights 2"
  #   state_topic: "/device/smartsocket/SMTSKT05/event"
  #   # command_topic: "/homeassistant/lights/kitchenbench"
  #   value_template: "{%if is_state(entity_id,\"on\")-%}OFF{%-else-%}ON{%-endif%}"

device_tracker:
  - platform: life360
    # https://www.home-assistant.io/components/life360/
    username: skelstar@gmail.com
    password: ec11225f87
    circles:
      include: [Family]

zone: !include zones.yaml

automation: !include automations.yaml

# deconz key E09E33DE20



