default_config:

homeassistant:
  # Location required to calculate the time the sun rises and sets
  latitude: -41.295160
  longitude: 174.765340
  elevation: 100
  # Name of the location where Home Assistant is running
  name: Home
  # C for Celcius, F for Fahrenheit
  temperature_unit: C
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Pacific/Auckland
  unit_system: metric

# -group: !include groups.yaml
# -script: !include scripts.yaml
# discovery:

# http:
#   api_password: dietpi
# WARNING (MainThread) [homeassistant.components.http] Configuring api_password via the http integration has been deprecated. Use the legacy api password auth provider instead. For instructions, see https://www.home-assistant.io/docs/authentication/providers/#legacy-api-password

mqtt:
  client_id: my_mqtt
  broker: 192.168.1.105

device_tracker:
  - platform: life360
    # https://www.home-assistant.io/components/life360/
    username: skelstar@gmail.com
    password: ec11225f87
    circles:
      include: [Family]

zone: !include zones.yaml

automation: !include automations.yaml

# deconz key E09E33DE20



